# Generated by Django 2.2.6 on 2019-10-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysoflogstoshow',
            name='days_to_show',
        ),
    ]
