# Generated by Django 2.2.6 on 2019-10-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0003_daysoflogstoshow_days_to_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarcraftLogsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_show', models.IntegerField()),
                ('api_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'WarcraftLogs Settings',
            },
        ),
        migrations.DeleteModel(
            name='DaysOfLogsToShow',
        ),
    ]
