# Generated by Django 2.2.6 on 2019-10-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0006_guildnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpfulGuildLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=255)),
                ('link_url', models.URLField()),
                ('link_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Helpful Guild Links',
            },
        ),
    ]
