# Generated by Django 2.2.6 on 2019-10-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0007_helpfulguildlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildAddonLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(max_length=255)),
                ('link_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Guild Addon Links',
            },
        ),
    ]
