# Generated by Django 2.2.7 on 2019-11-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0008_guildaddonlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=12)),
                ('character_realm', models.CharField(max_length=100)),
                ('character_class', models.CharField(max_length=20)),
                ('character_role', models.CharField(max_length=10)),
                ('character_level', models.IntegerField()),
                ('discord_username', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Guild Applicants',
            },
        ),
    ]
