# Generated by Django 2.2.7 on 2019-11-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0009_guildapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildapplications',
            name='application_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=20),
            preserve_default=False,
        ),
    ]
