# Generated by Django 2.2.7 on 2019-11-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0012_auto_20191120_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildapplications',
            name='application_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
