# Generated by Django 2.2.6 on 2019-11-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0013_auto_20191120_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlizzardApiSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Blizzard API Settings',
            },
        ),
    ]
