# Generated by Django 2.2.6 on 2019-11-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0015_auto_20191123_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildapplications',
            name='character_level',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='guildapplications',
            name='character_role',
            field=models.CharField(choices=[('Damage', 'Damage'), ('Healing', 'Healing'), ('Tank', 'Tank')], max_length=10),
        ),
    ]
