# Generated by Django 2.2.6 on 2019-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0016_auto_20191123_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildapplications',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='guildapplications',
            name='character_level',
        ),
        migrations.RemoveField(
            model_name='guildapplications',
            name='character_name',
        ),
        migrations.RemoveField(
            model_name='guildapplications',
            name='character_realm',
        ),
        migrations.RemoveField(
            model_name='guildapplications',
            name='character_role',
        ),
        migrations.AddField(
            model_name='guildapplications',
            name='character_armory_link',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
