# Generated by Django 2.2.6 on 2019-11-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0017_auto_20191123_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='blizzardapisettings',
            name='character_images_url',
            field=models.URLField(default='None'),
            preserve_default=False,
        ),
    ]
