# Generated by Django 2.2.6 on 2019-11-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0018_blizzardapisettings_character_images_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildapplications',
            name='character_image_url',
            field=models.URLField(default='None'),
            preserve_default=False,
        ),
    ]
