# Generated by Django 2.2.6 on 2019-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0020_auto_20191124_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blizzardapisettings',
            old_name='character_images_url',
            new_name='character_media_api_url',
        ),
        migrations.RenameField(
            model_name='blizzardapisettings',
            old_name='playable_class_url',
            new_name='character_profile_api_url',
        ),
        migrations.RenameField(
            model_name='blizzardapisettings',
            old_name='realms_api_url',
            new_name='token_api_url',
        ),
        migrations.AddField(
            model_name='blizzardapisettings',
            name='client_secret',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
