# Generated by Django 2.2.6 on 2019-11-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0021_auto_20191124_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildapplications',
            name='character_realm',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
