# Generated by Django 2.2.6 on 2019-11-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0022_guildapplications_character_realm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guildapplications',
            unique_together={('character_name', 'character_realm')},
        ),
    ]
