# Generated by Django 2.2.6 on 2019-11-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0023_auto_20191124_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='blizzardapisettings',
            name='guild_api_url',
            field=models.URLField(default='None'),
            preserve_default=False,
        ),
    ]
