# Generated by Django 2.2.6 on 2019-11-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0024_blizzardapisettings_guild_api_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_name', models.CharField(max_length=100)),
                ('guild_name_slug', models.SlugField()),
                ('guild_main_realm', models.CharField(max_length=100)),
                ('guild_ranks_to_query', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Guild Information',
            },
        ),
    ]
