# Generated by Django 2.2.6 on 2019-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0025_guildinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildinformation',
            name='guild_main_realm_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guildinformation',
            name='guild_name_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
