# Generated by Django 2.2.6 on 2019-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0029_guildinformation_guild_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildMOTD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateTimeField(auto_created=True)),
                ('guild_motd_desc', models.CharField(max_length=255)),
                ('guild_motd', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Guild Messages of the Day',
            },
        ),
    ]
