# Generated by Django 2.2.6 on 2019-12-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0030_guildmotd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raideriosettings',
            old_name='api_url',
            new_name='raid_progression_api_url',
        ),
        migrations.AddField(
            model_name='raideriosettings',
            name='raid_rankings_api_url',
            field=models.URLField(default='http://www.none.com'),
            preserve_default=False,
        ),
    ]
