# Generated by Django 2.2.6 on 2020-09-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0032_shadowlandsclasschart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadowlandsclasschart',
            name='shadowlands_first_choice',
            field=models.CharField(choices=[('TANK_DK', 'Tank Death Knight'), ('DPS_DK', 'DPS Death Knight'), ('TANK_DH', 'Tank Demon Hunter'), ('DPS_DH', 'DPS Demon Hunter'), ('TANK_DRUID', 'Tank Druid'), ('DPS_DRUID', 'DPS Druid'), ('HEALER_DRUID', 'Healer Druid'), ('HUNTER', 'Hunter'), ('MAGE', 'Mage'), ('TANK_MONK', 'Tank Monk'), ('DPS_MONK', 'DPS Monk'), ('HEALER_MONK', 'Healer Monk'), ('TANK_PALADIN', 'Tank Paladin'), ('DPS_PALADIN', 'DPS Paladin'), ('HEALER_PALADIN', 'Healer Paladin'), ('HEALER_PRIEST', 'Healer Priest'), ('DPS_PRIEST', 'DPS Priest'), ('ROGUE', 'Rogue'), ('HEALER_SHAMAN', 'Healer Shaman'), ('DPS_SHAMAN', 'DPS Shaman'), ('WARLOCK', 'Warlock'), ('TANK_WARRIOR', 'Tank Warrior'), ('DPS_WARRIOR', 'DPS Warrior')], default=None, max_length=50, verbose_name='Shadowlands Class First Choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shadowlandsclasschart',
            name='shadowlands_second_choice',
            field=models.CharField(blank=True, choices=[('TANK_DK', 'Tank Death Knight'), ('DPS_DK', 'DPS Death Knight'), ('TANK_DH', 'Tank Demon Hunter'), ('DPS_DH', 'DPS Demon Hunter'), ('TANK_DRUID', 'Tank Druid'), ('DPS_DRUID', 'DPS Druid'), ('HEALER_DRUID', 'Healer Druid'), ('HUNTER', 'Hunter'), ('MAGE', 'Mage'), ('TANK_MONK', 'Tank Monk'), ('DPS_MONK', 'DPS Monk'), ('HEALER_MONK', 'Healer Monk'), ('TANK_PALADIN', 'Tank Paladin'), ('DPS_PALADIN', 'DPS Paladin'), ('HEALER_PALADIN', 'Healer Paladin'), ('HEALER_PRIEST', 'Healer Priest'), ('DPS_PRIEST', 'DPS Priest'), ('ROGUE', 'Rogue'), ('HEALER_SHAMAN', 'Healer Shaman'), ('DPS_SHAMAN', 'DPS Shaman'), ('WARLOCK', 'Warlock'), ('TANK_WARRIOR', 'Tank Warrior'), ('DPS_WARRIOR', 'DPS Warrior')], max_length=50, null=True, verbose_name='Shadowlands Class Second Choice'),
        ),
        migrations.AlterField(
            model_name='shadowlandsclasschart',
            name='username',
            field=models.CharField(max_length=25, verbose_name='Current Main Name'),
        ),
        migrations.AlterUniqueTogether(
            name='shadowlandsclasschart',
            unique_together={('username', 'shadowlands_first_choice')},
        ),
        migrations.RemoveField(
            model_name='shadowlandsclasschart',
            name='shadowlands_class',
        ),
    ]
