# Generated by Django 2.2.6 on 2020-09-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posse', '0033_auto_20200914_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadowlandsclasschart',
            name='shadowlands_main',
            field=models.CharField(choices=[('TANK_DK', 'Tank Death Knight'), ('DPS_DK', 'DPS Death Knight'), ('TANK_DH', 'Tank Demon Hunter'), ('DPS_DH', 'DPS Demon Hunter'), ('TANK_DRUID', 'Tank Druid'), ('DPS_DRUID', 'DPS Druid'), ('HEALER_DRUID', 'Healer Druid'), ('HUNTER', 'Hunter'), ('MAGE', 'Mage'), ('TANK_MONK', 'Tank Monk'), ('DPS_MONK', 'DPS Monk'), ('HEALER_MONK', 'Healer Monk'), ('TANK_PALADIN', 'Tank Paladin'), ('DPS_PALADIN', 'DPS Paladin'), ('HEALER_PALADIN', 'Healer Paladin'), ('HEALER_PRIEST', 'Healer Priest'), ('DPS_PRIEST', 'DPS Priest'), ('ROGUE', 'Rogue'), ('HEALER_SHAMAN', 'Healer Shaman'), ('DPS_SHAMAN', 'DPS Shaman'), ('WARLOCK', 'Warlock'), ('TANK_WARRIOR', 'Tank Warrior'), ('DPS_WARRIOR', 'DPS Warrior')], default=None, max_length=50, verbose_name='Shadowlands Main'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shadowlandsclasschart',
            name='shadowlands_main_alt',
            field=models.CharField(blank=True, choices=[('TANK_DK', 'Tank Death Knight'), ('DPS_DK', 'DPS Death Knight'), ('TANK_DH', 'Tank Demon Hunter'), ('DPS_DH', 'DPS Demon Hunter'), ('TANK_DRUID', 'Tank Druid'), ('DPS_DRUID', 'DPS Druid'), ('HEALER_DRUID', 'Healer Druid'), ('HUNTER', 'Hunter'), ('MAGE', 'Mage'), ('TANK_MONK', 'Tank Monk'), ('DPS_MONK', 'DPS Monk'), ('HEALER_MONK', 'Healer Monk'), ('TANK_PALADIN', 'Tank Paladin'), ('DPS_PALADIN', 'DPS Paladin'), ('HEALER_PALADIN', 'Healer Paladin'), ('HEALER_PRIEST', 'Healer Priest'), ('DPS_PRIEST', 'DPS Priest'), ('ROGUE', 'Rogue'), ('HEALER_SHAMAN', 'Healer Shaman'), ('DPS_SHAMAN', 'DPS Shaman'), ('WARLOCK', 'Warlock'), ('TANK_WARRIOR', 'Tank Warrior'), ('DPS_WARRIOR', 'DPS Warrior')], max_length=50, null=True, verbose_name='Shadowlands Main Alt'),
        ),
        migrations.AlterUniqueTogether(
            name='shadowlandsclasschart',
            unique_together={('username', 'shadowlands_main')},
        ),
        migrations.RemoveField(
            model_name='shadowlandsclasschart',
            name='shadowlands_first_choice',
        ),
        migrations.RemoveField(
            model_name='shadowlandsclasschart',
            name='shadowlands_second_choice',
        ),
    ]
